["ui.cursor"]
fg = "blue"
bg = "default"
modifiers = ["reversed"]

["ui.cursor.primary"]
fg = "blue"
bg = "default"
modifiers = ["reversed"]

["ui.cursor.secondary"]
fg = "blue"
bg = "default"
modifiers = ["reversed"]

["ui.cursor.match"]
fg = "light-blue"
bg = "default"
modifiers = ["reversed", "bold"]

["ui.cursorline.primary"]
["ui.cursorline.primary.underline"]
color = "light-gray"
style = "dotted"

["ui.cursorcolumn.primary"]
fg = "white"
bg = "light-blue"

["ui.gutter"]
bg = "default"

["ui.gutter.selected"]
bg = "default"
modifiers = ["bold"]

["ui.linenr"]
modifiers = ["dim"]

["ui.linenr.selected"]
modifiers = ["bold"]

["ui.debug.breakpoint"]
fg = "red"
modifiers = ["bold"]

["ui.debug.active"]
fg = "yellow"
modifiers = ["bold"]

["ui.statusline"]
bg = "default"
modifiers = ["bold"]

["ui.statusline.separator"]
modifiers = ["dim"]

["ui.statusline.inactive"]
bg = "default"
modifiers = ["dim"]

["ui.statusline.normal"]
modifiers = ["bold"]

["ui.statusline.insert"]
fg = "0"
bg = "light-yellow"
modifiers = ["bold"]

["ui.statusline.select"]
fg = "white"
bg = "blue"
modifiers = ["bold"]

["ui.selection"]
fg = "light-blue"
bg = "default"
modifiers = ["reversed"]

["ui.menu.selected"]
fg = "light-blue"
bg = "default"
modifiers = ["reversed", "bold"]

["ui.menu.scroll"]
fg = "blue"
bg = "light-gray"

["ui.highlight"]
fg = "yellow"
bg = "light-blue"
modifiers = ["italic"]

["ui.text.focus"]
modifiers = ["bold"]

["ui.text.inactive"]
modifiers = ["dim"]

["ui.help"]
fg = "default"
bg = "default"

["ui.window"]
fg = "light-gray"
bg = "default"
modifiers = ["dim"]

["ui.virtual"]
fg = "light-gray"
modifiers = ["dim"]

["ui.virtual.ruler"]
bg = "gray"

["ui.virtual.whitespace"]
fg = "gray"
bg = "default"
modifiers = ["dim"]

["ui.virtual.indent-guide"]
fg = "light-gray"
modifiers = ["dim"]

["ui.virtual.inlay-hint"]
bg = "light-gray"

"warning" = "yellow"
"error" = "red"
"info" = "default"
"hint" = "cyan"
["diagnostic"]
["diagnostic.underline"]
color = "red"
style = "curl"

["diagnostic.hint"]
["diagnostic.hint.underline"]
color = "gray"
style = "curl"

["diagnostic.info"]
["diagnostic.info.underline"]
color = "cyan"
style = "curl"

["diagnostic.warning"]
["diagnostic.warning.underline"]
color = "yellow"
style = "curl"

["diagnostic.error"]
["diagnostic.error.underline"]
color = "red"
style = "curl"

["comment"]
fg = "gray"
modifiers = ["italic"]

["constant"]
fg = "yellow"
modifiers = ["bold"]

["constant.numeric"]
fg = "yellow"
modifiers = ["bold"]

["string"]
fg = "green"

["variable"]
modifiers = ["italic"]

["function"]
modifiers = ["bold"]

"tag" = "blue"
["namespace"]
modifiers = ["bold"]

["markup.heading"]
modifiers = ["bold"]

["markup.list"]
modifiers = ["bold"]

["markup.bold"]
modifiers = ["bold"]

["markup.italic"]
modifiers = ["italic"]

["markup.strikethrough"]
modifiers = ["dim", "crossed_out"]

"markup.link" = "blue"
["markup.quote"]
modifiers = ["italic"]

["markup.raw.block"]
modifiers = ["italic"]

["markup.raw.inline"]
modifiers = ["bold"]

"diff" = "default"
["diff.plus"]
modifiers = ["bold"]
fg = "green"

["diff.minus"]
fg = "red"
modifiers = ["bold"]

["diff.delta"]
modifiers = ["bold", "italic"]
fg = "yellow"

"diff.plus.gutter" = "green"
"diff.minus.gutter" = "red"
"diff.delta.gutter" = "yellow"
["keyword"]
fg = "blue"
modifiers = ["bold"]

["statement"]
fg = "blue"

["type"]
fg = "cyan"

["structure"]
fg = "cyan"

# -------------------
# Color Palette
# -------------------

# ANSI Color Names
#
# Idx  Name
# ---  -----------
#  -   default
#  0   black
#  1   red
#  2   green
#  3   yellow
#  4   blue
#  5   magenta
#  6   cyan
#  7   light-gray
#  8   gray
#  9   light-red
# 10   light-green
# 11   light-yellow
# 12   light-blue
# 13   light-magenta
# 14   light-cyan
# 15   white
