# macos.toml - macOS Application Manifest
#
# This manifest defines macOS-specific applications.
# CLI tools shared across platforms are defined in cli.toml.
#
# Supported installer types:
#   - dmg: macOS DMG installers
#
# Usage:
#   dev app install ghostty
#   dev app install --all
#   dev app status --all
#   dev app update --all

# =============================================================================
# GUI Applications (DMG)
# =============================================================================

[ghostty]
installer = "dmg"
url = "https://ghostty.org/download"
app = "Ghostty.app"
team_id = "24VZTF6M5V"
self_update = true  # Use Ghostty > Check for Updates
# user = false  # Install to /Applications (system-wide, default)

[zed]
installer = "curl"
url = "https://zed.dev/install.sh"
self_update = true  # Use Zed > Check for Updates
uninstall_cmd = "rm -rf /Applications/Zed.app ~/.local/bin/zed"
# Note: Zed installs to /Applications/Zed.app and symlinks CLI to ~/.local/bin/zed

# Example: User-scope DMG installation
# [example]
# installer = "dmg"
# url = "https://example.com/MyApp.dmg"
# app = "MyApp.app"
# team_id = "ABCDE12345"
# user = true  # Install to ~/Applications
